### ISSUE TITLE
Suggestion: Package dataURI as a joi extension

### ISSUE THREAD

**Issue by dekatron** [willy-b/joi-dataURI#2]
Hi,

I'm quite new to Joi but I wanted to use this package on a project at work and I noticed that you chose to wrap Joi instead of packaging dataURI as a Joi extension. I think that packaging it as an extension would be better as it would be more consistent with other extensions on npm and would make it easier to include other extensions along side dataURI.
```
const dateExtensions = require('joi-date-extensions');
const dataUri = require('./index.js')
const Joi = require('joi').extend([dateExtensions, dataUri]);
```
It also means that people can choose what version of Joi they want to use as it wouldn't be bundled with dataURI.

I've made a pull request which includes a version bump, I didn't know what versioning pattern you follow so I went with Semver since these would be breaking changes and packages like npm-check will recognise this as potentially breaking and flag it to anyone upgrading.

**Comment by willy-b** [comment]
This is awesome, thanks!

**Comment by willy-b** [comment]
resolved via https://github.com/willy-b/joi-dataURI/commit/89074da158a50429819704eae22140ad890abd04

**Comment by dekatron** [comment]
Cheers willy, could you publish to npm?

**Comment by willy-b** [comment]
Oops. Yes, updated in NPM now too! Thanks.

**Comment by dekatron** [comment]
Thanks :)
